//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutdownManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShutdownManager.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die activ ähnelt.
        /// </summary>
        public static string activ {
            get {
                return ResourceManager.GetString("activ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual Time ähnelt.
        /// </summary>
        public static string actualTime {
            get {
                return ResourceManager.GetString("actualTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual values ähnelt.
        /// </summary>
        public static string actualValues {
            get {
                return ResourceManager.GetString("actualValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock ähnelt.
        /// </summary>
        public static string clock {
            get {
                return ResourceManager.GetString("clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock trigger is activ ähnelt.
        /// </summary>
        public static string clockTriggerIsActiv {
            get {
                return ResourceManager.GetString("clockTriggerIsActiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PC is going to XXReplaceTemplateXX in XXReplaceTemplateTimeXX hours ähnelt.
        /// </summary>
        public static string createClockObservingMessage {
            get {
                return ResourceManager.GetString("createClockObservingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down- Upload observing is activ ähnelt.
        /// </summary>
        public static string downUploadIsActiv {
            get {
                return ResourceManager.GetString("downUploadIsActiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down/Upload observing ähnelt.
        /// </summary>
        public static string downUploadObserving {
            get {
                return ResourceManager.GetString("downUploadObserving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed Time: ähnelt.
        /// </summary>
        public static string elapsedTime {
            get {
                return ResourceManager.GetString("elapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inactiv ähnelt.
        /// </summary>
        public static string inactiv {
            get {
                return ResourceManager.GetString("inactiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PC is going to XXReplaceTemplateXX in 60 seconds! ähnelt.
        /// </summary>
        public static string lastBaloonTip {
            get {
                return ResourceManager.GetString("lastBaloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the Down-, Upload Control is active, it will check ähnelt.
        /// </summary>
        public static string mainUpDownLine1 {
            get {
                return ResourceManager.GetString("mainUpDownLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if the XXXInsertDownUploadXXX speed is under XXXInsertSpeedXXX MB/s ähnelt.
        /// </summary>
        public static string mainUpDownLine2 {
            get {
                return ResourceManager.GetString("mainUpDownLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for XXXInsertTimesXXX Times (s) then the PC will XXXInsertActionXXX ähnelt.
        /// </summary>
        public static string mainUpDownLine3 {
            get {
                return ResourceManager.GetString("mainUpDownLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No action was selected. Please select some action! ähnelt.
        /// </summary>
        public static string noActionSelected {
            get {
                return ResourceManager.GetString("noActionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no connection ähnelt.
        /// </summary>
        public static string noConnection {
            get {
                return ResourceManager.GetString("noConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Observe ähnelt.
        /// </summary>
        public static string observe {
            get {
                return ResourceManager.GetString("observe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Observing the Down/Upload is activ/inactiv! ähnelt.
        /// </summary>
        public static string observingDownUpBalloonTip {
            get {
                return ResourceManager.GetString("observingDownUpBalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart ähnelt.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds ähnelt.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep ähnelt.
        /// </summary>
        public static string sleep {
            get {
                return ResourceManager.GetString("sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Speed (MB/s)&quot; ähnelt.
        /// </summary>
        public static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer ähnelt.
        /// </summary>
        public static string timer {
            get {
                return ResourceManager.GetString("timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer is activ ähnelt.
        /// </summary>
        public static string timerActiv {
            get {
                return ResourceManager.GetString("timerActiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer has paused ähnelt.
        /// </summary>
        public static string timerPaused {
            get {
                return ResourceManager.GetString("timerPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer has started ähnelt.
        /// </summary>
        public static string timerStarted {
            get {
                return ResourceManager.GetString("timerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The timer is still running in the background ähnelt.
        /// </summary>
        public static string timerStillRunning {
            get {
                return ResourceManager.GetString("timerStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer has stopped ähnelt.
        /// </summary>
        public static string timerStopped {
            get {
                return ResourceManager.GetString("timerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger Now ähnelt.
        /// </summary>
        public static string triggerNow {
            get {
                return ResourceManager.GetString("triggerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger Time ähnelt.
        /// </summary>
        public static string triggerTime {
            get {
                return ResourceManager.GetString("triggerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Values ähnelt.
        /// </summary>
        public static string values {
            get {
                return ResourceManager.GetString("values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
